OWL-2825: Moved the delete button for Lessons
Western-OWL/sakai pull request #6
Opened 2017-07-06 17:42 UTC by ShadyLink

https://jira.uwo.ca/browse/OWL-2825

Less likely to accidentally click on the delete button accidentally when editing Lessons Items

2017-07-06 18:00 UTC, plukasew commented on lessonbuilder/tool/src/webapp/css/Simplepagetool.css
> +    float: right
Is this going to be too far to the right on wide screens and easily missed by users looking for it?

2017-07-10 13:41 UTC, fostersdesign commented on lessonbuilder/tool/src/webapp/css/Simplepagetool.css
> +    float: right
Now that it looks like a red button, will that help/resolve your concern, @plukasew ?

2017-07-10 13:48 UTC, plukasew commented on lessonbuilder/tool/src/webapp/css/Simplepagetool.css
> +    float: right
I'm still not sure the far right is the correct place for this on wider screens, but I suppose that is more of a responsive design issue. I think it is certainly more visible as a button though.

2017-07-10 13:53 UTC, bjones86 commented on lessonbuilder/tool/src/webapp/css/Simplepagetool.css
> +}*/
Can we just get rid of these comment blocks?

2017-07-10 15:50 UTC, ShadyLink commented on lessonbuilder/tool/src/webapp/css/Simplepagetool.css
> +}*/
Yep!

2017-07-10 15:51 UTC, ShadyLink commented
As discussed. The "Delete" link is now a button, and commented out code has been removed.

2017-07-10 20:39 UTC, fostersdesign requested changes
I like that the button is styled as a button now, but we don't have red delete buttons elsewhere in Sakai right now.

The correct fix options for this issue are:

1. add a confirmation prompt to the button in this panel similar to the confirmation on the main page (from the trash can icon)
2. or remove the delete button from the edit panel and make them use the trash can icon on the main page (similar to JIRA comments with the edit panel not having a delete button)

2017-07-12 13:18 UTC, ShadyLink commented
As per option 2. The button is now removed.

2017-07-12 21:00 UTC, closed without merging